[metadata]
name = "Nephrite Forest"
origin_url = "https://github.com/Nephrite-theme/terminal"

[colors]
background = "#0d1c14"
foreground = "#e0ebe5"
cursor_bg = "#4dbf74"
cursor_border = "#4dbf74"
cursor_fg = "#0d1c14"
selection_bg = "#324139"
selection_fg = "#e0ebe5"
split = "#25342c"
ansi = ["#25342c", "#ffa09c", "#4dbf74", "#d9bb5c", "#89c3fe", "#d0aafc", "#43d5dc", "#b4c1ba"]
brights = ["#76847c", "#ffa09c", "#5ed7b5", "#d9bb5c", "#89c3fe", "#f99dc6", "#43d5dc", "#e0ebe5"]

[colors.tab_bar]
background = "#050e09"

[colors.tab_bar.active_tab]
bg_color = "#0d1c14"
fg_color = "#e0ebe5"

[colors.tab_bar.inactive_tab]
bg_color = "#09150e"
fg_color = "#b4c1ba"

[colors.tab_bar.new_tab]
bg_color = "#050e09"
fg_color = "#b4c1ba"
