# Nephrite Forest for Kitty

foreground #e0ebe5
background #0d1c14
selection_foreground #e0ebe5
selection_background #324139
cursor #4dbf74
cursor_text_color #0d1c14
url_color #89c3fe

active_border_color #4dbf74
inactive_border_color #25342c
bell_border_color #d9bb5c

tab_bar_background #050e09
active_tab_foreground #e0ebe5
active_tab_background #0d1c14
inactive_tab_foreground #b4c1ba
inactive_tab_background #09150e

mark1_foreground #0d1c14
mark1_background #4dbf74
mark2_foreground #0d1c14
mark2_background #d9bb5c
mark3_foreground #0d1c14
mark3_background #d0aafc

color0 #25342c
color1 #ffa09c
color2 #4dbf74
color3 #d9bb5c
color4 #89c3fe
color5 #d0aafc
color6 #43d5dc
color7 #b4c1ba
color8 #324139
color9 #ffa09c
color10 #5ed7b5
color11 #d9bb5c
color12 #89c3fe
color13 #f99dc6
color14 #43d5dc
color15 #e0ebe5
