# Nephrite Mint for Kitty

foreground #192e23
background #edfbf3
selection_foreground #192e23
selection_background #bdd5c7
cursor #048149
cursor_text_color #edfbf3
url_color #2672b7

active_border_color #048149
inactive_border_color #cbe1d4
bell_border_color #866c02

tab_bar_background #c7ded1
active_tab_foreground #192e23
active_tab_background #edfbf3
inactive_tab_foreground #3f5247
inactive_tab_background #d7eadf

mark1_foreground #edfbf3
mark1_background #048149
mark2_foreground #edfbf3
mark2_background #866c02
mark3_foreground #edfbf3
mark3_background #8058ab

color0 #cbe1d4
color1 #ad4b4b
color2 #048149
color3 #866c02
color4 #2672b7
color5 #8058ab
color6 #017b80
color7 #3f5247
color8 #607268
color9 #ad4b4b
color10 #037e65
color11 #866c02
color12 #2672b7
color13 #a54a77
color14 #017b80
color15 #192e23
